export default function Privacy() {
  return <><header className="nav shell legal-nav"><a className="brand" href="/"><span className="brand-mark">P</span><span>PEACHTREE<br/><b>CAPITAL GROUP</b></span></a><a className="nav-cta" href="/">Return home →</a></header><main className="legal"><div className="legal-wrap"><p className="eyebrow">LEGAL</p><h1>Privacy Policy</h1><p className="updated">Effective date: July 29, 2026</p>
  <p>Peachtree Capital Group LLC (“Peachtree,” “we,” “our,” or “us”) respects your privacy. This Privacy Policy explains how we collect, use, disclose, and protect information when you visit our website, request a consultation, or communicate with us, including through our text messaging program.</p>
  <h2>Information we collect</h2><p>We may collect information you provide directly, including your name, business name, email address, mobile telephone number, financing goals, business details, and the content of communications with us. We may also collect device, browser, IP address, referral, and website usage information through cookies and similar technologies.</p>
  <h2>How we use information</h2><p>We use information to respond to inquiries; provide financial consulting services; evaluate potential capital programs; connect you with appropriate service providers when you request or authorize it; operate and improve our website; maintain security; comply with law; and send communications, including text messages when you have separately opted in.</p>
  <h2>How we disclose information</h2><p>We may disclose information to service providers that perform functions for us, professional advisers, regulators or law enforcement where legally required, and potential capital providers or other business partners when necessary to fulfill your request or with your direction. We may also disclose information in connection with a business transaction. We do not sell mobile opt-in data.</p>
  <p className="callout"><strong>Non-sharing Clause:</strong><br />No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. Information sharing to subcontractors in support services, such as customer service, is permitted. All other use case categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.</p>
  <h2>Text messaging data</h2><p>If you opt in to the Peachtree Capital Updates SMS Program, we use your mobile number and consent record only to operate that program and communicate with you as described in our Terms &amp; Conditions. Mobile opt-in information and consent are not shared with third parties or affiliates for marketing or promotional purposes.</p>
  <h2>Cookies and analytics</h2><p>We may use necessary, preference, and analytics cookies to operate the site and understand how visitors use it. You can control cookies through your browser settings, though disabling them may affect site functionality.</p>
  <h2>Data retention and security</h2><p>We retain information for as long as reasonably necessary for the purposes described above and to meet legal obligations. We use reasonable administrative, technical, and physical safeguards, but no transmission or storage system can be guaranteed completely secure.</p>
  <h2>Your choices</h2><p>You may request access, correction, or deletion of your personal information, subject to applicable exceptions, by contacting us. You may unsubscribe from email using the link provided in an email. To stop text messages, reply STOP to any message. For text help, reply HELP.</p>
  <h2>Children’s privacy</h2><p>Our services are intended for business owners and adults and are not directed to children under 18. We do not knowingly collect personal information from children.</p>
  <h2>Changes to this policy</h2><p>We may update this policy from time to time. The effective date above indicates the latest revision. Material changes will be posted on this page.</p>
  <h2>Contact us</h2><p>Questions or privacy requests may be sent to Peachtree Capital Group LLC at <a href="mailto:info@peachtree.capital"><u>info@peachtree.capital</u></a>.</p></div></main></>;
}
